// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `dbDoKhi`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=dbDoKhi;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using Dapper;

namespace DoKhi.Models
{
	public partial class dbDoKhi_NameConnectionStringConfig
    {
        public static string NameConnectionStringConfig = "dbDoKhi";
    }


	public partial class DiemDoRepository : Repository<DiemDoObject>
    {
		 public override string NameConnectionStringConfig => dbDoKhi_NameConnectionStringConfig.NameConnectionStringConfig;
	}

    /// <summary>
    /// A class which represents the DiemDo table.
    /// </summary>
	[Table("DiemDo")]
	public partial class DiemDoObject
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string OPC_Address { get; set; }
		public virtual int? Type { get; set; }
		public virtual bool? Active { get; set; }
	}


	public partial class DaThongSoRepository : Repository<DaThongSoObject>
    {
		 public override string NameConnectionStringConfig => dbDoKhi_NameConnectionStringConfig.NameConnectionStringConfig;
	}

    /// <summary>
    /// A class which represents the DaThongSo table.
    /// </summary>
	[Table("DaThongSo")]
	public partial class DaThongSoObject
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Name { get; set; }
		public virtual string OPC_Address { get; set; }
		public virtual bool? Active { get; set; }
	}

}
